### PR TITLE
new custom category filter

### PR DESCRIPTION
**Pull request by cbalit**

### CODE REVIEW

**Comment by AshDevFr** [comment]
I don't really like using DOM manipulation in the JS.
Maybe we could just take the whole list of categories and return an Array.join() to display the list

**Comment by florianorpeliere** [comment]
:+1: @AshDevFr --force

**Comment by AshDevFr** [comment]
@cbalit my idea: [step-19-solution-newFilter](https://github.com/AshDevFr/blogular/tree/step-19-solution-newFilter)

**Comment by AshDevFr** [comment]
A new filter has been added, I will use your solution in the future when i'll explain $sanitize.

**Pull request closed without merging**
